Updates and corrections
NCAR/atmospheric_physics pull request #52
Opened 2022-02-09 05:41 UTC by gold2718

Update metadata
Remove unsupported optional `metadata` keyword
Add constituent info to metadata (i.e., `advected` property)
Rewrite wet_to_dry_to_wet converters to be proper CCPP
Add qneg_namelist.xml

fixes #51 
fixes #48

2022-02-09 05:43 UTC, gold2718 commented
@nusbaume, Kessler still has an issue because the CCPP Framework is getting confused by multiple schemes in a file (the converters) and is sometimes getting the wrong module for an input variable (so physics_inputs.F90 does not compile).
I will work on a fix for that.

2022-02-09 18:44 UTC, peverwhee approved these changes
looks good to me

2022-12-21 16:40 UTC, nusbaume requested changes
Looks good, but I did have a few units and namelist XML questions that I would like to get resolved before testing and merging.

Also @gold2718 if you feel like you won't have time to make any changes then I am happy to do them for you, as long as you are ok with me either pushing to your branch, or opening a PR.  Just let me know!

2022-12-22 17:41 UTC, gold2718 commented on utilities/qneg.meta
> +  units = None
Agreed (and this was true even back in February).

2022-12-22 18:18 UTC, gold2718 commented on utilities/qneg_namelist.xml
> +<?xml-stylesheet type="text/xsl" href="namelist_definition.xsl"?>
It's the *old* 2-file format (currently only existing in CTSM)!
Removed the `href`, we should propagate this change around (e.g., to CDEPS which also has this useless appendage).

2022-12-22 18:18 UTC, gold2718 commented on utilities/qneg_namelist.xml
> +     that the attribute values are enclosed in quotes.  The attributes are:
Great but use the new version.

2022-12-22 18:18 UTC, gold2718 commented on utilities/qneg_namelist.xml
> +          CCSM inputdata directory tree.  Note that the variables
You have something against history?

2022-12-22 18:18 UTC, gold2718 commented on utilities/qneg_namelist.xml
> +                                                                        -->
Good idea, added.

2022-12-23 18:42 UTC, nusbaume approved these changes
I am happy with this PR once gold2718#1 has been merged/resolved.

2022-12-23 21:20 UTC, nusbaume approved these changes

2022-12-23 21:20 UTC, merged